export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';

export const LOGIN_FACEBOOK_SUCCESS = 'LOGIN_FACEBOOK_SUCCESS';

export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';

export const ADD_PUBLICATION_SUCCESS = 'ADD_PUBLICATION_SUCCESS';
export const ADD_PUBLICATION_REQUEST = 'ADD_PUBLICATION_REQUEST';
export const ADD_PUBLICATION_ERROR = 'ADD_PUBLICATION_ERROR';

export const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS';
export const GET_PUBLICATIONS_SUCCESS = 'GET_PUBLICATIONS_SUCCESS';
export const GET_PUBLICATIONS_ERROR = 'GET_PUBLICATIONS_ERROR';
export const GET_PUBLICATIONS_REQUEST = 'GET_PUBLICATIONS_REQUEST';

export const GET_USER_ID_SUCCESS = 'GET_USER_ID_SUCCESS';
export const GET_USER_ID_REQUEST = 'GET_USER_ID_SUCCESS';
export const GET_USER_ID_ERROR = 'GET_USER_ID_SUCCESS';

export const GET_PUBLICATIONS_ID_SUCCESS = 'GET_PUBLICATIONS_ID_SUCCESS';
export const GET_PUBLICATIONS_ID_REQUEST = 'GET_PUBLICATIONS_ID_REQUEST';
export const GET_PUBLICATIONS_ID_ERROR = 'GET_PUBLICATIONS_ID_ERROR';

export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';

export const SUBSCRIBE_USER_SUCCESS = 'SUBSCRIBE_USER_SUCCESS';

